/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.odev2;

import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
/**
 *
 * @author teoman
 */
public class girisEkrani extends javax.swing.JFrame {
    
    private final String TXT_YOLU = "C:\\P2Oyun\\TXTDosyalar\\";
    private final String SIFRE_DOSYASI = TXT_YOLU + "sifre.txt";
    private final String LOG_DOSYASI = TXT_YOLU + "log.txt";
    
    private int hataliGirisSayisi=0;
    private boolean sifreVarMi = false;
    private String kayitliSifre ="";
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(girisEkrani.class.getName());

    /**
     * Creates new form girisEkrani
     */
    public girisEkrani() {
        initComponents();
        baslangicKontrol();
    }

    private void logYaz(String mesaj){
        try{
            FileWriter fw = new FileWriter(LOG_DOSYASI,true);
            PrintWriter pw = new PrintWriter(fw);
            
            LocalDateTime simdi = LocalDateTime.now();
            DateTimeFormatter format = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            String tarihSaat = simdi.format(format);
            
            pw.println("["+ tarihSaat +"] "+mesaj);
            pw.close();
        }
        catch(IOException e){
            System.out.println("Log yazılamadı: "+ e.getMessage());
        }
    }
    
    private void baslangicKontrol(){
        File dosya = new File(SIFRE_DOSYASI);
        
        if(dosya.exists() && dosya.length() > 0){
            sifreVarMi = false;
            lblMesaj.setText("Şifre girin: ");
            
            try{
                BufferedReader br= new BufferedReader(new FileReader(dosya));
                kayitliSifre = br.readLine();
                br.close();
            }
            catch(IOException e){
                System.out.println("Hata!!!!!");
            }
        }
        else{
            sifreVarMi = true;
            lblMesaj.setText("Şifre belirlenmemiş!! Aşağıya yazarak şifrenizi oluşturun.");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMesaj = new javax.swing.JLabel();
        txtSifre = new javax.swing.JPasswordField();
        btnGiris = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMesaj.setText("jLabel1");

        btnGiris.setText("GİRİŞ");
        btnGiris.addActionListener(this::btnGirisActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(btnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 76, Short.MAX_VALUE)
                .addComponent(lblMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(73, Short.MAX_VALUE)
                .addComponent(lblMesaj, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSifre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        String girilenSifre = new String(txtSifre.getPassword());
        
        if(girilenSifre.equals("")){
            JOptionPane.showMessageDialog(this, "Lütfen bir şifre giriniz!");
            return;
        }
        
        if(sifreVarMi){
            try{
                FileWriter fw = new FileWriter(SIFRE_DOSYASI);
                fw.write(girilenSifre);
                fw.close();
                
                logYaz("Şifre oluşturuldu.");
                JOptionPane.showMessageDialog(this, "Şifre kaydedildi. Giriş yap.");
                
                sifreVarMi = false;
                kayitliSifre = girilenSifre;
                lblMesaj.setText("Şifre girin: ");
                txtSifre.setText("");
            }
            catch(IOException e){
                JOptionPane.showMessageDialog(this, "Hata! Şifre kaydedilemedi.");
            }
        }
        else{
            if(girilenSifre.equals(kayitliSifre)){
                logYaz("Giriş Yapıldı.");
                
               JOptionPane.showMessageDialog(this, "Giriş yapıldı. Oyun açılıyor...");
               oyunEkrani oyun = new oyunEkrani();
               oyun.setVisible(true);
               this.dispose(); // dispose: giriş ekranını kapatma satırı!!! ram'i meşgul etmesin!
            }
            else{
                hataliGirisSayisi++;
                logYaz("Hatalı deneme! (Deneme: "+ hataliGirisSayisi + ")");
                
                if(hataliGirisSayisi>=3){
                    logYaz("Maksimum deneme hakkı! Kapatıldı!");
                    JOptionPane.showMessageDialog(this, "Maksimum denemeye ulaşıldı! Kapatılıyor...");
                    System.exit(0); // programı kapatma satırı 
                }
                else{
                    JOptionPane.showMessageDialog(this, "Şifre hatalı! Kalan deneme: "+ (3-hataliGirisSayisi));
                    txtSifre.setText("");
                }
            }
        }
    }//GEN-LAST:event_btnGirisActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new girisEkrani().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGiris;
    private javax.swing.JLabel lblMesaj;
    private javax.swing.JPasswordField txtSifre;
    // End of variables declaration//GEN-END:variables
}
